#%RAML 1.0 Library

securitySchemes:
  ########################## EXTERNAL SECURITY SCHEMAS ##########################
  clientSecurity: !include exchange_modules/9b8efe00-883f-40ec-913d-12759bd40702/abc-auth-security/1.0.1/abc-auth-security.raml
traits:
  ########################## EXTERNAL TRAITS ##########################
  ErrorResponse: !include exchange_modules/9b8efe00-883f-40ec-913d-12759bd40702/abc-error-responses/1.0.0/abc-error-responses.raml
  Pageable: !include exchange_modules/9b8efe00-883f-40ec-913d-12759bd40702/abc-pagination-trait/1.0.0/abc-pagination-trait.raml

  ########################## INTERNAL TRAITS ##########################

  Queryable:
    queryParameters:
      departmentId?: DepartmentId
      name?:
        type: string
        example: Human Resource

types:
  ########################## EXTERNAL DATA TYPES ##########################
  Department: !include exchange_modules/9b8efe00-883f-40ec-913d-12759bd40702/abc-department/1.0.1/abc-department.raml
  Response: !include exchange_modules/9b8efe00-883f-40ec-913d-12759bd40702/abc-api-response/1.0.1/abc-api-response.raml
  PingResponse: !include exchange_modules/9b8efe00-883f-40ec-913d-12759bd40702/abc-ping-response/1.0.1/abc-ping-response.raml

  ########################## INTERNAL DATA TYPES ##########################
  DepartmentId: 
    type: string
    displayName: Department ID
    description: Unique department ID, every employee belongs to at least one department.
    pattern: ^\w{2,3}$
    example: ITR