#%RAML 1.0 Library

securitySchemes:
  ########################## EXTERNAL SECURITY SCHEMAS ##########################
  clientSecurity: !include exchange_modules/9b8efe00-883f-40ec-913d-12759bd40702/abc-auth-security/1.0.1/abc-auth-security.raml
traits:
  ########################## EXTERNAL TRAITS ##########################
  ErrorResponse: !include exchange_modules/9b8efe00-883f-40ec-913d-12759bd40702/abc-error-responses/1.0.0/abc-error-responses.raml

  ########################## INTERNAL TRAITS ##########################
  Pageable:
    queryParameters:
      page?:
        type: number
        displayName: Page Number
        description:  A specific page to retrieve resources from server
        example: 10
      size?:
        type: number
        displayName: Page Size
        description: A number will restrict the server response to max 200 items.
        maximum: 200
        example: 100

  Queryable:
    queryParameters:
      departmentId?: DepartmentId
      name?:
        type: string
        example: Human Resource

types:
  ########################## EXTERNAL DATA TYPES ##########################
  Department: !include exchange_modules/9b8efe00-883f-40ec-913d-12759bd40702/abc-department/1.0.1/abc-department.raml
  Response: !include exchange_modules/9b8efe00-883f-40ec-913d-12759bd40702/abc-api-response/1.0.1/abc-api-response.raml
  PingResponse: !include exchange_modules/9b8efe00-883f-40ec-913d-12759bd40702/abc-ping-response/1.0.1/abc-ping-response.raml

  ########################## INTERNAL DATA TYPES ##########################
  DepartmentId: 
    type: string
    displayName: Department ID
    description: Unique department ID, every employee belongs to at least one department.
    pattern: ^\w{2,3}$
    example: ITR