#%RAML 1.0
title: sys-org-services-api
securedBy:
  - Library.clientSecurity

# baseUri: http://localhost:8081/api

description: This API exposes resources that are essential for organization.

uses:
  Library: library.raml

types:
  CreateDepartmentRequest: !include dataTypes/requests/createDepartmentRequest.raml
  UpdateDepartmentRequest: !include dataTypes/requests/updateDepartmentRequest.raml
  CreateBranchRequest: !include dataTypes/requests/createBranchRequest.raml
  UpdateBranchRequest: !include dataTypes/requests/updateBranchRequest.raml

  GetDepartmentResponse: !include dataTypes/responses/getDepartmentResponse.raml
  GetBranchResponse: !include dataTypes/responses/getBranchResponse.raml
  PingResponse: Library.PingResponse

/ping:
  get:
    is: [Library.ErrorResponse]
    responses:
      200:
        body:
          application/json: PingResponse

/branches:
  get:
    is: 
      - Library.ErrorResponse
      - Library.Pageable
      - Library.DepartmentQueryable
    responses:
      200:
        body:
          application/json: GetBranchResponse

  post:
    is: [Library.ErrorResponse]
    body:
      application/json: CreateBranchRequest
    responses:
      201:
        body:
          application/json: Library.Response
          example: !include examples/responses/createBrachResponse.json
  put:
  delete:

/departments:
  get:
    is: 
      - Library.ErrorResponse
      - Library.Pageable
      - Library.DepartmentQueryable

    responses:
      200:
        body:
          application/json: GetDepartmentResponse
          
  post:
    is: 
      - Library.ErrorResponse

    body:
      application/json: CreateDepartmentRequest
    responses:
      201:
        body:
          application/json: 
            type: Library.Response
            example: !include examples/responses/createDepartmentResponse.json

  /{ID}:
    uriParameters:  
      ID: Library.DepartmentId

    put:
      is: 
        - Library.ErrorResponse
      body:
        application/json: UpdateDepartmentRequest

      responses:
        200:
          body:
            application/json: 
              type: Library.Response
              example: !include examples/responses/updateDepartmentResponse.json

    delete:
      is: 
        - Library.ErrorResponse
      responses:
        200:
          body:
            application/json:
              type: Library.Response
              example: !include examples/responses/deleteDepartmentResponse.json